name: Build and deploy WAR app to Azure Web App - raas-searoute

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'microsoft'

      - name: Build WAR with Maven (from submodule)
        run: mvn -f modules/war clean package

      - name: Upload WAR artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-war
          path: 'modules/war/target/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-war

      - name: Deploy WAR to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'raas-searoute'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.war'
